mysite/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from .views import (
    login_view,
    logout_view,
    get_cookie_view,
    set_cookie_view,
    set_session_view,
    get_session_view,
    MyLogoutView,
    AboutMeView,
    RegisterView,
    FooBarView,
    HelloView, 
    edit_profile,
)

app_name = 'myauth'

urlpatterns = [
    # path("login/", login_view, name='login'),
    path("login/",
         LoginView.as_view(
             template_name="myauth/login.html",
             redirect_authenticated_user=True
         ),
         name='login'),

    path('hello/', HelloView.as_view(), name='hello'),

    # path('logout/', MyLogoutView.as_view(), name='logout'),
    path('logout/', logout_view, name='logout'),
    path("about-me/", AboutMeView.as_view(), name='about-me'),
    path('register/', RegisterView.as_view(), name='register'),
    path('edit/', edit_profile, name='edit'),
    
    path('cookie/get/', get_cookie_view, name='cookie-get'),
    path('cookie/set/', set_cookie_view, name='cookie-set'),

    path('session/set/', set_session_view, name='session-set'),
    path('session/get/', get_session_view, name='session-get'),

    path('foo-bar/', FooBarView.as_view(), name='foo-bar')
]

mysite/mysite/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('req/', include('requestdataapp.urls')),
    path('api/', include('myapiapp.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('myauth/', include('myauth.urls')),
    path('shop/', include('shop.urls')),
    
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )
    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls)),
    )

mysite/shop/urls.py
from django.urls import path, include

from rest_framework.routers import DefaultRouter

from .views import (
    ShopIndexView,
    GroupsListView,
    ProductDetailsView,
    ProductsListView,
    OrdersListView,
    OrderDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    ProductsDataExportView,
    ProductViewSet,
    OrderViewSet,
)

app_name = 'shop'

routers = DefaultRouter()
routers.register("products", ProductViewSet)
routers.register("orders", OrderViewSet)

urlpatterns = [
    path('', ShopIndexView.as_view(), name='index'),
    path('api/', include(routers.urls)),
    path('groups/', GroupsListView.as_view(), name='groups'),
    path('products/', ProductsListView.as_view(), name='products'),
    path('products/<int:pk>/', ProductDetailsView.as_view(), name='product_details'),
    path('products/create/', ProductCreateView.as_view(), name='create_product'),
    path('products/export/', ProductsDataExportView.as_view(), name='products-export'),
    path('products/<int:pk>/update/', ProductUpdateView.as_view(), name='update_product'),
    path('products/<int:pk>/archived/', ProductDeleteView.as_view(), name='delete_product'),
    path('orders/', OrdersListView.as_view(), name='orders'),
    path("orders/<int:pk>/", OrderDetailView.as_view(), name='order_details')
]

mysite/myauth/models.py
from django.contrib.auth.models import User
from django.db import models

def generate_user_avatar_path(instance, filename):
    return f"users/user_{instance.user.pk}/avatar/{filename}"


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    agreement_accepted = models.BooleanField(default=False)
    avatar = models.ImageField(null=True, blank=True, upload_to=generate_user_avatar_path)
    
    

mysite/myauth/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Profile

class EditProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = 'username', 'first_name', 'last_name', 'email'
        
class AvatarForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = 'avatar',

mysite/myauth/views.py
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LogoutView
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import TemplateView, CreateView
from django.utils.translation import gettext_lazy as _, ngettext

from django.utils.translation import gettext_lazy as _, ngettext

from .models import Profile
from .forms import EditProfileForm, AvatarForm 


class HelloView(View):
    welcome_message = _('welcome hello world')
    def get(self, request: HttpRequest) -> HttpResponse:
        
        items_str = request.GET.get('items') or 0
        items = int(items_str)
        
        products_line = ngettext(
            "one product",
            "{count} products",
            items,
        )
        
        products_line = products_line.format(count=items)
        
        return HttpResponse(
            f'<h1>{self.welcome_message}</h1>'
            f'\n<h2>{products_line}</h2>'
            )


class HelloView(View):
    welcome_message = _("welcome hello world")

    def get(self, request: HttpRequest) -> HttpResponse:

        items_str = request.GET.get('items') or 0
        items = int(items_str)
        products_line = ngettext(
            "one product",
            "{count} products",
            items,
        )
        products_line = products_line.format(count=items)
        return HttpResponse(
            f"<h1>{self.welcome_message}</h1>"
            f"\n<h2>{products_line}</h2>"

        )


class AboutMeView(TemplateView):
    template_name = "myauth/about-me.html"


class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = "myauth/register.html"
    success_url = reverse_lazy("myauth:about-me")

    def form_valid(self, form):
        response = super().form_valid(form)
        Profile.objects.create(user=self.object)
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(
            self.request,
            username=username,
            password=password
        )
        login(request=self.request, user=user)
        return response

def login_view(request: HttpRequest) -> HttpResponse:
    if request.method == 'GET':
        if request.user.is_authenticated:
            return redirect('/admin/')
    return render(request, 'myauth/login.html')

    username = request.POST['username']
    password = request.POST['password']

    user = authenticate(request, username=username, password=password)
    if user is not None:
        return render(request, 'myauth/login.html', {"error": "Invalid login credentials"})



def logout_view(request: HttpRequest):
    logout(request)
    return redirect(reverse("myauth:login"))


class MyLogoutView(LogoutView):
    next_page = reverse_lazy("myauth:login")


@user_passes_test(lambda u: u.is_superuser)
def set_cookie_view(request: HttpRequest) -> HttpResponse:
    response = HttpResponse("Cookie set")
    response.set_cookie("fizz", "buzz", max_age=3600)
    return response


def get_cookie_view(request: HttpRequest) -> HttpResponse:
    value = request.COOKIES.get("fizz", "default value")
    return HttpResponse(f"Cookie value: {value!r}")


@permission_required("myauth.view_profile", raise_exception=True)
def set_session_view(request: HttpRequest) -> HttpResponse:
    request.session["foobar"] = "spameggs"
    return HttpResponse('Session set')


@login_required
def get_session_view(request: HttpRequest) -> HttpResponse:
    value = request.session.get('foobar', 'default value')
    return HttpResponse(f"Session value {value!r}")


class FooBarView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        return JsonResponse({"foo": "bar", "spam": "eggs"})


@login_required
def edit_profile(request: HttpRequest) -> HttpResponse:
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)
        profile, created = Profile.objects.get_or_create(
            user=request.user
        )
        form_av = AvatarForm(request.POST, request.FILES, instance=profile)
        
        if form.is_valid() and form_av.is_valid():
            form.save()
            form_av.save()
            
            return redirect('myauth:about-me')
    else:
        form = EditProfileForm(instance=request.user)
        profile, created = Profile.objects.get_or_create(
            user=request.user
        )
        form_av = AvatarForm(instance=profile)
        
    context = {
        "form": form,
        "form_av": form_av,
    }
    return render(request, 'myauth/edit-profile.html', context=context)

mysite/myauth/templates/myauth/about-me.html
{% extends 'myauth/base.html' %}

{% block title %}
    About me
{% endblock %}

{% block body %}
    <h1>User info</h1>
    {% if user.is_authenticated %}
        <h2>Detail</h2>
        <img src="{{ user.profile.avatar.url }}" alt="{{ user.profile.avatar.name }}">
        <p>Username: {{ user.username }}</p>
        <p>First name: {{ user.first_name }}</p>
        <p>Last name: {{ user.last_name }}</p>
        <p>Email: {{ user.email }}</p>
        <p>Bio: {{ user.profile.bio }}</p>

        <div>
            <a href="{% url 'myauth:edit' %}">Edit profile</a>
        </div>
    {% else %}
        <h2>User is anonymous</h2>
    {% endif %}
{% endblock %}

mysite/myauth/templates/myauth/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Auth
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
    <!-- <link rel="stylesheet" href="{% static 'css/style.css' %}"> -->
</head>
<body>
    {% block body %}

    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>


<!-- <!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
  </head>
  <body>
    <h1>Hello, world!</h1>
  </body>
</html> -->

mysite/myauth/templates/myauth/edit-profile.html
{% extends 'myauth/base.html' %}

{% block body %}

<form method="post" enctype="multipart/form-data">
    <h1>Change Public Info</h1>
    <hr>
    {% csrf_token %}
    {{ form.as_p }}
    {{ form_av.as_p }}

    <button type="submit">Save Changes</button>
    <div>
        <a href="{% url 'myauth:about-me' %}">Bact to Your Page</a>
    </div>
</form>

{% endblock %}

mysite/myauth/templates/myauth/login.html
{% extends 'myauth/base.html' %}

{% block title %}
    Login
{% endblock %}

{% block body %}

    <form method="post">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">Login</button>
    </form>
{% endblock %}

mysite/myauth/templates/myauth/register.html
{% extends "myauth/base.html" %}

{% block title %}
    Register
{% endblock %}

{% block body %}
    <h1>Register</h1>
    <form id="barev" class="kikos" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
        <input type="text">
        <input class="submitButton" type="submit" value="Register">
    </form>
    <!-- <div class="input-group flex-nowrap">
        <span class="input-group-text" id="addon-wrapping">@</span>
        <input type="text" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="addon-wrapping">
    </div> -->
{% endblock %}