mysite/mysite/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('req/', include('requestdataapp.urls')),
    path('api/', include('myapiapp.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('myauth/', include('myauth.urls')),
    path('shop/', include('shop.urls')),
    
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )
    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls)),
    )

mysite/shop/urls.py
from django.urls import path, include

from rest_framework.routers import DefaultRouter

from .views import (
    ShopIndexView,
    GroupsListView,
    ProductDetailsView,
    ProductsListView,
    OrdersListView,
    OrderDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    ProductsDataExportView,
    ProductViewSet,
    OrderViewSet,
)

app_name = 'shop'

routers = DefaultRouter()
routers.register("products", ProductViewSet)
routers.register("orders", OrderViewSet)

urlpatterns = [
    path('', ShopIndexView.as_view(), name='index'),
    path('api/', include(routers.urls)),
    path('groups/', GroupsListView.as_view(), name='groups'),
    path('products/', ProductsListView.as_view(), name='products'),
    path('products/<int:pk>/', ProductDetailsView.as_view(), name='product_details'),
    path('products/create/', ProductCreateView.as_view(), name='create_product'),
    path('products/export/', ProductsDataExportView.as_view(), name='products-export'),
    path('products/<int:pk>/update/', ProductUpdateView.as_view(), name='update_product'),
    path('products/<int:pk>/archived/', ProductDeleteView.as_view(), name='delete_product'),
    path('orders/', OrdersListView.as_view(), name='orders'),
    path("orders/<int:pk>/", OrderDetailView.as_view(), name='order_details')
]

mysite/shop/models.py
from django.contrib.auth.models import User
from django.db import models


def product_preview_directory_path(instance: 'Product', filename: str) -> str:
    return "products/product_{pk}/preview/{filename}".format(
        pk=instance.pk,
        filename=filename
    )


class Product(models.Model):
    """
    Represents a product in the inventory.

    Attributes:
        id (int): The unique identifier for the product.
        name (str): The name of the product.
        price (float): The price of the product.
        description (str): A brief description of the product.


    Orders here :model:`shop.Order`
    """
    class Meta:
        ordering = ['name', 'price']
        # db_table = 'tech_product'
        # verbose_name_plural = 'products'
        # verbose_name = _("Product")
        # app_label = 'mysite'

    name = models.CharField(max_length=100, db_index=True)
    description = models.TextField(null=False, blank=True, db_index=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.SmallIntegerField(default=0)
    created_at = models.TimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)
    preview = models.ImageField(null=True, blank=True, upload_to=product_preview_directory_path)

    # @property
    # def short_description(self):
    #     if len(self.description) < 48:
    #         return self.description
    #     else:
    #         return self.description[:48] + '...'
    def __str__(self) -> str:
        return f'Product(pk={self.pk}, name={self.name!r})'


def product_images_directory_path(instance: 'ProductImage', filename: str) -> str:
     return f"products/product_{instance.product.pk}/images/{filename}"

class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to=product_images_directory_path)
    description = models.CharField(max_length=200, null=True, blank=True)


class Order(models.Model):
    delivery_address = models.TextField(null=True, blank=True)
    promocode = models.CharField(max_length=20, null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name='orders')
    receipt = models.FileField(null=True, upload_to='orders/receipts')
    

mysite/shop/forms.py
from django import forms
from django.forms.utils import flatatt
from django.utils.safestring import mark_safe

from django.contrib.auth.models import Group
from django.core import validators

from shop.models import Product


# class ProductForm(forms.Form):
#     name = forms.CharField(max_length=100)
#     price = forms.DecimalField(min_value=1, max_value=100000)
#     description = forms.CharField(
#         label='Product description',
#         widget=forms.Textarea(attrs={"rows": 5, "cols": '33'}),
#         validators=[validators.RegexValidator(
#             regex=r'great',
#             message='Field must contain word great'
#         )],
#     )

# class ProductForm(forms.ModelForm):
#     class Meta:
#         model = Product
#         fields = "name", "price", "description", "discount"


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ["name"]


class MultipleClearableFileInput(forms.ClearableFileInput):
    def render(self, name, value, attrs=None, renderer=None):
        if value is None:
            value = []

        final_attrs = self.build_attrs(attrs, {'type': 'file', 'name': name, 'multiple': 'multiple'})
        input_html = '<input{} />'.format(flatatt(final_attrs))

        return mark_safe(input_html)

    def value_from_datadict(self, data, files, name):
        if isinstance(files.get(name), list):
            return files.getlist(name)
        return files.get(name, None)


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["name", "price", "description", "discount", "preview", "images"]

    images = forms.ImageField(widget=MultipleClearableFileInput)




# class ProductForm(forms.ModelForm):
#     class Meta:
#         model = Product
#         fields = "name", "price", "description", "discount", "preview"
#
#     images = forms.ImageField(
#         widget=forms.ClearableFileInput(attrs={'multiple': True}),
#     )

mysite/shop/views.py
"""
The views module contains view functions for handling HTTP requests and rendering web pages.

This module includes view functions for various aspects of the web application, such as
displaying product listings.

Functions:
    index: Renders the index page of the shop application.
    product_detail: Renders the detail page for a specific product.
    process_order: Handles order processing.
    api_product_list: Returns a JSON response containing a list of products (API endpoint).
    api_product_detail: Returns a JSON response containing details of a specific product (API endpoint)
"""

import logging
from timeit import default_timer


from django.http import HttpRequest, HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth.models import Group
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from rest_framework.viewsets import ModelViewSet
from rest_framework.filters import SearchFilter, OrderingFilter
from django_filters.rest_framework import DjangoFilterBackend
from drf_spectacular.utils import extend_schema, OpenApiResponse
from .forms import ProductForm, GroupForm
from .models import Product, Order, ProductImage
from .serializers import ProductSerializer, OrderSerializer


logger = logging.getLogger(__name__)


# @extend_schema(description='Product CRUD')
class ProductViewSet(ModelViewSet):
    """
    A view set for interacting with the product resource.

    This view set provides CRUD (Create, Retrieve, Update, Delete) operations
    for the product resource. It supports listing all products, creating a new product,
    retrieving a specific product by ID, updating an existing product, and deleting a product.

    Attributes:
        queryset (QuerySet): The queryset representing all products in the database.
        serializer_class (Serializer): The serializer class used to serialize/deserialize
            product instances.
    """
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    filter_backends = [
        SearchFilter,
        DjangoFilterBackend,
        OrderingFilter,
    ]
    search_fields = ["name", "description",]
    filterset_fields = [
        "name",
        "description",
        "price",
        "discount",
        "archived"
    ]
    ordering_fields = [
        "name",
        "price",
        "discount",
    ]

    @extend_schema(
        summary='Get one product by ID',
        description='Retrieves **product**, returns 404 if not found',
        responses={
            200: ProductSerializer,
            404: OpenApiResponse(description='Empty response, product by id not found'),
        }
    )
    def retrieve(self, *args, **kwargs):
        return super().retrieve(*args, **kwargs)


class OrderViewSet(ModelViewSet):

    queryset = Order.objects.all()
    serializer_class = OrderSerializer
    filter_backends = [
        DjangoFilterBackend,
        SearchFilter,
        OrderingFilter
    ]
    search_fields = [
        "delivery_address", 'user'
    ]

    filterset_fields = [
        'delivery_address',
        'promocode',
        'user'
    ]

    ordering_fields = [
        'created_at',
        'user'
    ]
class ShopIndexView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        products = [
            ('Laptop', 1999),
            ('Desktop', 2999),
            ('Smartphone', 999),
        ]
        context = {
            'time_running': default_timer(),
            'products': products,
            'items': 1,
        }
        logger.debug("Products %s" % products)
        logger.info("Rendering shop index")
        return render(request, 'shop/index.html', context=context)


class GroupsListView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        context = {
            "form": GroupForm(),
            'groups': Group.objects.all()
        }
        return render(request, 'shop/groups.html', context=context)

    def post(self, request: HttpRequest):
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()

        return redirect(request.path)



class ProductDetailsView(DetailView):
    template_name = 'shop/products-details.html'
    model = Product
    context_object_name = "product"


class ProductsListView(ListView):
    template_name = 'shop/products.html'
    # model = Product
    queryset = Product.objects.filter(archived=False)
    context_object_name = 'products'


class ProductCreateView(UserPassesTestMixin, CreateView):
    def test_func(self):
        # return self.request.user.groups.filter(name='secret-group').exists()
        return self.request.user.is_superuser

    model = Product
    fields = "name", "price", "description", "discount", "preview"
    # form_class = ProductForm
    success_url = reverse_lazy("shop:products")


class ProductUpdateView(UpdateView):
    model = Product
    # fields = "name", "description", "price", "discount", "preview"
    template_name_suffix = "_update_form"
    form_class = ProductForm

    def get_success_url(self):
        return reverse(
            "shop:product_details",
            kwargs={'pk': self.object.pk},
        )

    def form_valid(self, form):
        response = super().form_valid(form)
        for image in form.files.getlist("images"):
            ProductImage.objects.get_or_create(
                product=self.object,
                image=image,
            )

        return response
class ProductDeleteView(DeleteView):
    # model = Product
    queryset = Product.objects.prefetch_related("images")
    success_url = reverse_lazy('shop:products')

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)


class OrdersListView(LoginRequiredMixin, ListView):
    queryset = (
        Order.objects
        .select_related('user')
        .prefetch_related('products')
        .all()
    )


class OrderDetailView(PermissionRequiredMixin, DetailView):
    permission_required = ["shop.view_order",]
    queryset = (
        Order.objects
        .select_related('user')
        .prefetch_related('products')
    )


class ProductsDataExportView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        products = Product.objects.order_by("pk").all()
        products_data = [
            {
                "pk": product.pk,
                "name": product.name,
                "price": product.price,
                "archived": product.archived,
            }
            for product in products
        ]
        elem = products_data[0]
        name = elem['name']
        print(name)
        return JsonResponse({"products": products_data})

mysite/shop/templates/shop/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Base Title
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    
</head>
<body>

{% block body %}
    Base Body
{% endblock %}
<div>
    {% now 'H:i' %}
</div>

<div>
    {% now 'l' as weekday %}
    Today is {{ weekday }}
</div>
</body>
</html>

mysite/shop/templates/shop/create-product.html
{% extends 'shop/base.html' %}

{% block title %}
    Create product
{% endblock %}

{% block body %}
    <h1>Create a new product</h1>
    <div>
    <form method="post">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">
            Create
        </button>
    </form>
    </div>

    <div>
    <a href="{% url 'shop:products' %}"
    >Back to products list</a>
    </div>

{% endblock %}

mysite/shop/templates/shop/groups.html
{% extends 'shop/base.html' %}

{% block title %}
    Groups
{% endblock %}

{% block body %}
    <h1>Groups:</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
    <div>
        <ul>
            {% if not groups %}
                <h3>No groups yet</h3>
            {% else %}
            <ul>
                {% for group in groups %}
                <li>
                    <div>{{ group.name }}</div>
                    <ul>
                        {% for permission in group.permissions.all %}
                            <li>
                                {{ permission.name }}
                                (<code>{{ permission.codename }}</code>)
                            </li>
                        {% endfor %}
                    </ul>
                </li>
                {% endfor %}
            </ul>
            {% endif %}
    </div>
{% endblock %}

mysite/shop/templates/shop/index.html
{% extends 'shop/base.html' %}

{% block title %}
    Shop Title
{% endblock %}

{% block body %}
    <h1>Shop Index</h1>
    <div>
        Time running: {{ time_running }}
    </div>

    <div>
        <ul>
            {% for name, price in products %}
                <li>{{ name }} ({{ name|length }}) for ${{ price }}</li>
                {% if name|length_is:'7' %}
                    <span>Lucky product</span>
                {% endif %}
            {% empty %}
                No products here
            {% endfor %}
        </ul>

    </div>

    <div>
        <strong>
            You have {{ items }} cherr{{ items|pluralize:"y,ies"}}
        </strong>
    </div>

    <div>
        {% lorem 3 p random %}
    </div>
{% endblock %}

mysite/shop/templates/shop/order_detail.html
{% extends 'shop/base.html' %}

{% block title %}
    Order #{{ object.pk }} details
{% endblock %}

{% block body %}
<h1>Order #{{ object.pk }}</h1>
    <div>
        <p>Order by: {% firstof object.user.username object.user.firstname %}</p>
        <p>Promocode <code>{{ object.promocode }}</code></p>
        <p>Delivery address: {{ object.delivery_address }}</p>
    <div>
        <div>
            Products in order:
            <ul>
                {% for product in object.products.all %}
                    <li>{{product.name}} for ${{product.price}}</li>
                {% endfor %}
            </ul>
        <div>

    <div>
        <a href="{% url 'shop:orders' %}">Back to orders</a>
    </div>
{% endblock %}

mysite/shop/templates/shop/order_list.html
{% extends 'shop/base.html' %}

{% block title %}
    Orders list
{% endblock %}

{% block body %}
    <h1>Orders:</h1>
    {% if object_list %}
        <div>
        {% for order in object_list %}
            <div>
                <p><a href="{% url 'shop:order_details' pk=order.pk %}"
                >Details #{{ order.pk }}</a> </p>
                <p>Order by: {% firstof order.user.username order.user.firstname %}</p>
                <p>Promocode <code>{{ order.promocode }}</code></p>
                <p>Delivery address: {{ order.delivery_address }}</p>
                <div>
                    Products in order:
                    <ul>
                        {% for product in order.products.all %}
                            <li>{{product.name}} for ${{product.price}}</li>
                        {% endfor %}
                    </ul>
                </div>
        {% endfor %}
        </div>
    {% else %}
        <p>No orders yet</p>
    {% endif %}

{% endblock %}

mysite/shop/templates/shop/product_confirm_delete.html
{% extends 'shop/base.html' %}

{% block title %}
    Confirm archive {{ object.name }}
{% endblock %}

{% block body %}
    <h1>Are you sure you want to archive {{ object.name }}?</h1>
    <br>
    <div>
        <a href="{% url 'shop:product_details' pk=object.pk %}"
        >Back to product</a>
    </div>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Archive</button>
        </form>
    </div>
{% endblock %}

mysite/shop/templates/shop/product_form.html
{% extends 'shop/base.html' %}

{% block title %}
    Create product
{% endblock %}

{% block body %}
    <h1>Create product</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
    <div>
        <a href="{% url 'shop:products' %}">Back to products</a>
    </div>
{% endblock %}

mysite/shop/templates/shop/product_update_form.html
{% extends 'shop/base.html' %}

{% block title %}
    Update product
{% endblock %}

{% block body %}
    <h1>Update product</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update</button>
        </form>
    </div>
    <div>
        <a href="{% url 'shop:product_details' pk=object.pk %}">Back to product #{{ object.pk }}</a>
    </div>
{% endblock %}

mysite/shop/templates/shop/products-details.html
{% extends 'shop/base.html' %}

{% block title %}
    Product #{{product.pk}}
{% endblock %}

{% block body %}
    <h1>Product <strong>{{ product.name }}</strong></h1>
    <div>
        <div>Description: <em>{{ product.description }}</em></div>
        <div>Price: {{ product.price }}</div>
        <div>Discount: {{ product.discount }}</div>
        <div>Archived: {{ product.archived }}</div>

        {% if product.preview %}
            <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
        {% endif %}
        <h3>Images</h3>
        <div>
            {% for img in product.images.all %}
                <div>
                    <img src="{{ img.image.url }}" alt="{{ img.image.name }}">
                <div>{{ img.description }}</div>
                </div>
            {% empty %}
                <div>No images uploaded yet</div>
            {% endfor %}
        </div>
    </div>
    <div>
        <a href="{% url 'shop:products' %}">Back to products</a>
    </div>

    <div>
        <a href="{% url 'shop:update_product' pk=product.pk %}">Update product</a>
    </div>

    <div>
        <a href="{% url 'shop:delete_product' pk=product.pk %}">Archive product</a>
    </div>
{% endblock %}

mysite/shop/templates/shop/products.html
{% extends 'shop/base.html' %}

{% load i18n %}


{% block title %}
    {% translate 'Products list' %}
{% endblock %}

{% block body %}
    <h1>{% translate 'Products' %}:</h1>
    {% if products %}
        <div>
        {% blocktranslate count products_count=products|length %}
            There is only one product.
            {% plural %}
            There are {{ products_count }} products. 
        {% endblocktranslate %}
        </div>
    <div>
        {% for product in products %}
            <div>
                <p><a href="{% url 'shop:product_details' pk=product.pk %}"
                >{% translate 'Name' %}: {{ product.name }}</a></p>
                <p>{% translate 'Price' %}: {{ product.price }}</p>
                {% translate 'no discount' as no_discount %}
                <p>{% translate 'Discount' %}: {% firstof product.discount no_discount %}</p>

                {% if product.preview %}
                     <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}">
                {% endif %}
            </div>

        {% endfor %}

    </div>

    <div>
        <a href="{% url 'shop:create_product' %}"
        >{% translate 'Create a new product' %}</a>
    </div>

    {% else %}
        {% url 'shop:create_product' as create_product_url %}
        {% blocktranslate %}
            <h3>No products yet</h3>
            <a href="{{ create_product_url }}"
            >Create a new one</a>
        {% endblocktranslate %}
    {% endif %}
{% endblock %}